name: CI

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_on_push:
        description: 'Run workflow for push events (true/false)'
        required: true
        default: 'true'
      run_on_pull_request:
        description: 'Run workflow for pull request events (true/false)'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' && 
      ( (github.event.inputs.run_on_push == 'true' && github.ref == 'refs/heads/test') || 
        (github.event.inputs.run_on_pull_request == 'true' && github.ref == 'refs/heads/main') ) || 
      github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
